### PR TITLE
Fix/help messages

### PR DESCRIPTION
**Pull request by shyba**
Hey,

I was trying to plot and got lost. While trying I got some errors and checked the code.

The first commit fixes a bug when just one input file isn't found. (raised error before)
The second one fixes a bug when the only file passed doesn't exists (also raised).
One additional help message is printed for clarifications on use of last profile data.

Hope it helps :D

### CODE REVIEW

**Comment by shyba** [comment]
Example after fix:
```
✗ mprof plot --output=plot3.png sdfsdf 1 2 3
Input file not found: sdfsdf
✗ mprof plot --output=plot3.png sdfsdf
Input file not found: sdfsdf
No files found from given input.
✗ mprof plot --output=plot3.png
Using last profile data.
```

**Comment by fabianp** [comment]
Great! Do you mind putting parenthesis around `print` so its also python3 compatible, e.g. print(something) ?

Thanks

**Comment by shyba** [comment]
Fixed!
Thank you for maintaining the project. It is helping me a lot.

**Comment by fabianp** [comment]
Glad to hear that, thanks for your contribution!

**Pull request merged**
