### PR TITLE
Bug Fix: memory_usage hangs on exception #152

### PR DESCRIPTION
**Pull request by mhaseebtariq**
https://github.com/fabianp/memory_profiler/issues/152

### CODE REVIEW

**Comment by mhaseebtariq** [comment]
@fabianp

**Comment by fabianp** [comment]
hi @mhaseebtariq and thanks for the patch. A couple of things:

  * Please do not wrap the entire function inside a try/catch. The function memory_usage is very general, and can for example get memory usage from other programs (via its PID) in which case the try/except block would just mask other issues. Limit the try/catch block to where the Python function is being called (I think this should be the line "returned = f(*args, **kw)").

   * Use sys.stderr.write to write to stderr for consistency with previous code.

**Comment by mhaseebtariq** [comment]
Thanks @fabianp I have made the changes! Does the pull request look fine now! :)

**Comment by fabianp** [comment]
It does look fine! I added one more commit and pushed the whole thing. In this commit I added:

  * A non-regression test.
  * Slight change in the logic, in which in the parent thread I raise an exception instead of killing the whole program. This might be better behaved in the case in which the memory_usage function is itself inside a try/catch block. Let me know if you find any issues with it.

Thanks!

**Comment by mhaseebtariq** [comment]
@fabianp I have tested - It's working as expected now! Thanks very much! :)

**Pull request merged**
